version: '3.5'
services:
  php:
    build: .
    user: app
    working_dir: /app
    command: ["php-fpm", "-F"]
    volumes:
        - .:/app:cached
        - cache:/app/var/cache
        - vendor:/app/vendor
  database:
    image: mariadb:10.3
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: test
  nginx:
    image: nginx:1.14.0-alpine
    ports:
      - "3001:80"
    working_dir: /app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app:cached
      - cache:/app/var/cache
      - vendor:/app/vendor
    depends_on:
      - php
volumes:
    cache:
    vendor:
    database:
